### ISSUE TITLE
HTML report enabled would be a nice-to-have...

### ISSUE THREAD

**Issue by jorgevila** [arturdm/jacoco-android-gradle-plugin#10]

**Comment by arturdm** [comment]
@jorgevila please look in `build/reports/jacoco/jacocoTest<variant>UnitTestReport` directory after running the `jacocoTestReport` task. Is there an `html` directory or just an `xml` file?

The default behavior is for `JacocoTestReport` tasks to create an HTML report (https://docs.gradle.org/current/userguide/jacoco_plugin.html). Additionally, this plugin also enables xml reports.

**Comment by arturdm** [comment]
@jorgevila - you can try the latest version now (0.1.1). It lets you toggle report generation by type. Hope it helps.
