### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/dicedmelon/gradle/jacoco/android/JacocoAndroidPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by tommytcchan** [arturdm/jacoco-android-gradle-plugin#11]
Hi there,

I'm running compile version 1.7

```    
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
```

However I am setting the error in the title when I run ```./gradlew jacocoTestReport```

Any ideas here? Thanks

**Comment by tommytcchan** [comment]
@arturdm any suggestions? thanks

**Comment by arturdm** [comment]
The plugin was build using JDK 1.8 and that's the reason for the failure. You can try setting `JAVA_HOME` to point to jdk1.8 directory and append jdk8's bin directory to your `PATH`, e.g.:

```
PATH=/path-to-jdk8/bin:$PATH JAVA_HOME=/path-to-jdk8 ./gradlew jacocoTestReport
```

If that doesn't help I'll publish an updated version which works with Java 7 soon.

**Comment by arturdm** [comment]
@tommytcchan - you can try the latest version now (0.1.1). It should fix the issue and also adds some minor features.

**Comment by tommytcchan** [comment]
Great thanks a bunch!
