### ISSUE TITLE
Outdated jacoco version 

### ISSUE THREAD

**Issue by WarrenFaith** [arturdm/jacoco-android-gradle-plugin#17]
Is there any way to define which jacoco version will be used?

I just tested your plugin on a newly created app and it downloads a pretty old version of jacoco 0.7.1.201405082137

**Comment by arturdm** [comment]
You can try to add this block to the root of your application/library module's `build.gradle` like this:

```
apply plugin: 'com.android.application'
apply plugin: 'jacoco-android'

android { ... }

jacoco {
  toolVersion = "0.7.5.201505241946"
}
```

Please, rememeber to `clean` your project after you change this version.

**Comment by WarrenFaith** [comment]
Works like charm! Thank you!
