### ISSUE TITLE
Slow task lookup when there are a lot of variants

### ISSUE THREAD

**Issue by simtel12** [arturdm/jacoco-android-gradle-plugin#45]
Due to flavor dimensions our project ends up having 320 variants, and gradle configuration takes about 20 seconds per run.  Working with @oehme, he discovered that at least 25% of the time spent is on one line in the jacoco plugin:  https://github.com/arturdm/jacoco-android-gradle-plugin/blob/b976c3c1da400fd5e0824c4455400be2d8d741dc/src/main/groovy/com/dicedmelon/gradle/jacoco/android/JacocoAndroidPlugin.groovy#L93

The search is quadratic in the number of variants, and it seems like a simple `getByName` should work instead of the search.

**Comment by arturdm** [comment]
fixed by #46
