### ISSUE TITLE
Error building with Android Studio 3.3.1

### ISSUE THREAD

**Issue by af-abe** [arturdm/jacoco-android-gradle-plugin#59]
I got this error

```* What went wrong:
Execution failed for task ':sharedcomponents:jacocoDev'.
> There was a failure while executing work items
   > A failure occurred while executing com.android.build.gradle.internal.tasks.JacocoTaskDelegate$JacocoWorkerAction
      > java.lang.ExceptionInInitializerError (no error message)
```

i am using Android Studio 3.3.1 with gradle 4.10.1 and gradle plugin 3.3.1

**Comment by mTwTm** [comment]
I'm seeing something similar without upgrading to Android Studio 3.3.1 but only Gradle 4.10

```
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.12 and you are trying to load version 2.4.15
	... 20 more
```

**Comment by haamaanaa** [comment]
Any solution for this one?

I just "found" it as well....

**Comment by haamaanaa** [comment]
`buildscript {
    configurations.all { exclude module:"groovy-all"}
}`

that apparently fixes it....

**Comment by arturdm** [comment]
@af-abe could you also check if it occurs the latest [0.1.4](https://github.com/arturdm/jacoco-android-gradle-plugin/releases/tag/jacoco-android-release-0.1.4) release?

**Comment by af-abe** [comment]
> @af-abe could you also check if it occurs the latest [0.1.4](https://github.com/arturdm/jacoco-android-gradle-plugin/releases/tag/jacoco-android-release-0.1.4) release?

nice... 0.1.4 is working without `configurations.all { exclude module:"groovy-all"}`

**Comment by devilk10** [comment]
Throwing ---> java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedSerializationConstructorAccessor1  ---- when ./gradlew jacocoTestReport ran
