### ISSUE TITLE
Not showing proper coverage on sonarQube with this plugin

### ISSUE THREAD

**Issue by ShreyashPromact** [arturdm/jacoco-android-gradle-plugin#71]
Here I am using Jococo Android Plugin
When I use `sonar.jacoco.reportPaths` for my Android Project to report code coverage it shows the coverage properly, but when I use `sonar.coverage.jacoco.xmlReportPaths` then it is not showing coverage for the same code on sonarQube. Either there is an issue with the format provided by Jococo & SonarQube for the Code Coverage file.

### Steps to reproduce
A configured project with the deprecated property of Sonar, that is `sonar.jacoco.reportPaths`, You will get Warning on SonarQube server to use a new property instead of the deprecated ones. You can also see the code coverage ersults on SonarQube. Now use the new property `sonar.coverage.jacoco.xmlReportPaths` & comment the deprecated property `sonar.jacoco.reportPaths`. Now, execute the analysis on sonarQube. See that the code coverage is 0.0% on SonarQube server.

JaCoCo version: `com.dicedmelon.gradle:jacoco-android:0.1.4`
Operating system: `Windows 10`
Tool integration: `Gradle/Java, toolVersion: "0.8.3"`

### Expected behavior
It should generate and upload the code-coverage report in a supported format so that sonarQube can identify the code-coverage of the code.

### Actual behavior
It is showing **0.0%** code-coverage on sonarQube with `sonar.coverage.jacoco.xmlReportPaths`.

**Comment by ShreyashPromact** [comment]
Can anyone provide an update on this.
Thanks.

**Comment by jangrewe** [comment]
Works fine for me:
```
property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml"
```

**Comment by ShreyashPromact** [comment]
@jangrewe 
Thanks for posting. In my case, it was regarding the jacoco plugin. it was not installed on sonar cloud. So we have added it an it is now showing code-coverage.
