### ISSUE TITLE
groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'executionData' for task ':legacy:jacocoTest[BuildVariant]UnitTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

### ISSUE THREAD

**Issue by mochadwi** [arturdm/jacoco-android-gradle-plugin#77]
Gradle Wrapper:  `6.0.1-all`
AS & Gradle Tools: `3.5.2` 
Gradle: Kotlin DSL
Kotlin: 1.3.50

https://docs.gradle.org/current/dsl/org.gradle.testing.jacoco.tasks.JacocoReport.html
<img width="549" alt="Screen Shot 2019-12-15 at 4 09 56 AM" src="https://user-images.githubusercontent.com/7057959/70854625-c25bc580-1ef0-11ea-9f5c-feb7e6818cf8.png">

It says on the Gradle `JacocoReport` docs that 6.0.1 above now have the permission of `read-only`.

Is jacoco-android still not support **6.0.1**?

Also, looks like this is related to this issue #72 if related, I'll close this issue, otherwise will leave it open

**Comment by mochadwi** [comment]
https://github.com/arturdm/jacoco-android-gradle-plugin/pull/75#issuecomment-565222643

In fact, I'm using the forked version now from @autonomousapps thanks man

**Comment by stamanker** [comment]
how to solve this?

**Comment by Ankitazaptas** [comment]
Remove in module level gradle with latter
 compileOptions
            {
                sourceCompatibility defaultJavaVersion.VERSION_1_8
                targetCompatibility defaultJavaVersion.VERSION_1_8
            }
 compileOptions
            {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
