### ISSUE TITLE
No repository found for 0.1.5-SNAPSHOT

### ISSUE THREAD

**Issue by risurabhi** [arturdm/jacoco-android-gradle-plugin#87]
Hi

We are using jacoco-android plugin. We started seeing this error.

Could not find com.dicedmelon.gradle:jacoco-android:0.1.5-SNAPSHOT.

Has the repository been moved? 

Thanks & Regards
Surabhi

**Comment by meiyank** [comment]
Facing same issue.

**Comment by viceboyz** [comment]
Facing Same issue

**Comment by mnkshukl** [comment]
Same issue no version of snapshot present

**Comment by mnaturel-niji** [comment]
We have the same issue as well.

**Comment by nicolasfanin** [comment]
Facing same issue

**Comment by AnelCC** [comment]
Same here.

**Comment by arturdm** [comment]
Hi all,

@risurabhi please try out the latest snapshot and check if it works for you.

```
buildscript {
  repositories {
    ...
    maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots' }
  }
  dependencies {
    ...
    classpath 'com.dicedmelon.gradle:jacoco-android:0.1.5-SNAPSHOT'
  }
}
```

Guide also available here https://github.com/arturdm/jacoco-android-gradle-plugin#snapshot-usage

**Comment by risurabhi** [comment]
Thanks, I was able to resolve the issue by using the new repository path.

**Comment by dev-Paras-and** [comment]
@arturdm Thanks, It is working now. 

When can we expect stable 0.1.5?

**Comment by arturdm** [comment]
@dev-Paras-Ind It's available here https://plugins.gradle.org/plugin/com.dicedmelon.gradle.jacoco-android.

You can apply it using Kotlin DSL too:

```
plugins {
  id "com.dicedmelon.gradle.jacoco-android" version "0.1.5"
}
```

or using legacy plugin application (note the plugin id change):

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.dicedmelon.gradle:jacoco-android:0.1.5"
  }
}

apply plugin: "com.dicedmelon.gradle.jacoco-android"
```
